model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 512
  input_size: 256
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000
  hidden_dims: [32, 64, 128, 256, 512, 1024]

data_params:
  data_path: "/home/ubuntu/efs/datasets"
  train_batch_size: 64
  val_batch_size:  64
  test_batch_size: 64
  patch_size: 256
  num_workers: 4
  dataset: 'CelebA'
  
exp_params:
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  devices: "auto"
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  manual_seed: 1265
  name: 'BetaVAE'
