model_params:
  name: 'HVAE'
  in_channels: 3
  img_size: 64
  latent1_dim: 64
  latent2_dim: 64
  pseudo_input_size: 128

data_params:
  data_path: "/home/ubuntu/efs/datasets"
  train_batch_size: 64
  val_batch_size: 64
  test_batch_size: 64
  patch_size: 64
  num_workers: 4
  dataset: 'CelebA'


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  devices: "auto"
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VampVAE"
