model_params:
  name: 'IWAE'
  in_channels: 3
  latent_dim: 128
  input_size: 64
  num_samples: 5

data_params:
  data_path: "/home/ubuntu/efs/datasets"
  train_batch_size: 64
  val_batch_size: 64
  test_batch_size: 64
  patch_size: 64
  num_workers: 4
  dataset: 'CelebA'


exp_params:
  LR: 0.007
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  devices: "auto"
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "IWAE"
